# =============================================================================
# Copyright 2024, SuperNDA. All rights reserved.
# =============================================================================

:verbose: true
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:max_retries: 0

:queues:
  - [default, 1]
  - [mailers, 2]
  - [high_priority, 3]
