# =============================================================================
# Copyright 2024, SuperNDA. All rights reserved.
# =============================================================================

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  endpoint: <%= ENV["DIGITAL_OCEAN_ENDPOINT"] %>
  access_key_id: <%= ENV["DIGITAL_OCEAN_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["DIGITAL_OCEAN_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["DIGITAL_OCEAN_BUCKET"] %>
  region: <%= ENV["DIGITAL_OCEAN_REGION"] %>